### PR TITLE
Added uECC_compute_public_key.

### PR DESCRIPTION
**Pull request by ricmoo**
I also added this, if you are interested in adding it. Sometimes I just store the private key and want to generate the public key from that, rather than storing the entire key pair.

The test case was more for my own sanity, to make sure things compiled properly and whatnot. You probably don't require it.

### CODE REVIEW

**Comment by ricmoo** [comment]
I've made the changes you suggested, you should see them in the pull request now. I kept everything as separate commits, as there is now a slight change in behaviour for `uECC_make_key`.

Previously, if the key generation failed, the output buffers passed in were untouched. They may now have "junk" public keys in them.

I could also factor out the `uECC_compute_public_key` into a new function, `compute_public_key` which would deal with the native data structures, and then make `uECC_compute_public_key` just a thin wrapper around that with native-to-byte conversions. This would also allow us to not have to convert the native private key back into bytes to pass into `uECC_compute_public_key` in `uECC_make_key`.

Let me know what you think.

**Comment by ricmoo** [comment]
I made the changes that better abstract computing the public key.

I tried to keep in style with parameter naming conventions, parameter order (internal has output first, external has output last), et cetera. But please let me know if there is anything you'd like changed.

Thanks.

**Comment by kmackay** [comment]
Looks good. The only other thing is that you don't need to check vli_isZero(l_private) in uECC_make_key() anymore, since it is checked in EccPoint_compute_public_key().

**Comment by ricmoo** [comment]
Haha. I think I committed that at the same time you commented. Either way, done. :)

The deterministic signing is coming along well too. Just have to properly implement bits2int and write test cases.

**Comment by kmackay** [comment]
Thanks!

**Pull request merged**
